name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  workflow_dispatch:              # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, activity, community, repositories, metadata"
          template: repository  # <--- this is the template, e.g. classic / terminal / markdown etc.
